heat_template_version: 2015-04-30

description: >
  Deployment of a single python server for the first part of inf4410_TP3

parameters:
  parameters:
    image_id:
      type: string
      label: Image ID
      description: Image to be used for compute instance
      default: INF4410-Ubuntu-trusty-mini
    instance_type:
      type: string
      label: Instance Type
      description: Type of instance (flavor) to be used
      defaut: INF4410-mini
    net_id:
      type: string
      description: network id
      default: inf4410-net


resources:
  single_server:
    type: OS::Nova::Server
    properties:
      name: "single_server"
      image: { get_param: image_id }
      flavor: { get_param: instance_type }
      networks:
        - network: {get_param: net_id}
outputs:
  instance_ip:
    description: The IP address of the deployed instance
    value: { get_attr: [my_instance, first_address] }

